# Generated by Django 3.1.6 on 2021-02-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_end',
            field=models.DateTimeField(verbose_name='end of reservation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_start',
            field=models.DateTimeField(verbose_name='start of reservation'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closing_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_time',
            field=models.TimeField(),
        ),
    ]
